[package]
name = "tatoeba"
version = "0.1.0"
authors = ["Maxime “pep” Buquet <pep@bouah.net>"]

[dependencies]
chrono = "0.4.0"
dotenv = "0.10.1"

[dependencies.diesel]
features = ["mysql", "extras"]
version = "0.16.0"

[dependencies.diesel_codegen]
features = ["mysql"]
version = "0.16.0"
